"""Initial schema

Revision ID: 7fb95318bd4b
Revises: 
Create Date: 2026-07-15 01:37:57.621135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb95318bd4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('year_founded', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('matchup', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('player_game_stats',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.String(length=10), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('field_goals_made', sa.Integer(), nullable=False),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=False),
    sa.Column('three_pointers_made', sa.Integer(), nullable=False),
    sa.Column('three_pointers_attempted', sa.Integer(), nullable=False),
    sa.Column('free_throws_made', sa.Integer(), nullable=False),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=False),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('personal_fouls', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('team_game_stats',
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.String(length=10), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('field_goals_made', sa.Integer(), nullable=False),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=False),
    sa.Column('three_pointers_made', sa.Integer(), nullable=False),
    sa.Column('three_pointers_attempted', sa.Integer(), nullable=False),
    sa.Column('free_throws_made', sa.Integer(), nullable=False),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=False),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('personal_fouls', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_game_stats')
    op.drop_table('player_game_stats')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('players')
    # ### end Alembic commands ###
